// <auto-generated />
using System;
using Kiwbi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiwbi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KiwbiDbContext))]
    [Migration("20260914225128_AddCustomizations")]
    partial class AddCustomizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiwbi.Domain.Customizations.Customization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TradeCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_category_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TradeCategoryId", "Name")
                        .IsUnique();

                    b.ToTable("customizations", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.Customizations.TradeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HousingPromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("housing_promotion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("SelectionCutOffDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selection_cut_off_date_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("HousingPromotionId", "Name")
                        .IsUnique();

                    b.ToTable("trade_categories", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.Developers.DeveloperCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("developer_companies", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeveloperCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_company_id");

                    b.Property<string>("MasterPlanImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("master_plan_image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperCompanyId");

                    b.ToTable("housing_promotions", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingTypology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HousingPromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("housing_promotion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("HousingPromotionId", "Name")
                        .IsUnique();

                    b.ToTable("housing_typologies", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuiltAreaSqm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("built_area_sqm");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Door")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("door");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("floor");

                    b.Property<string>("FloorPlanImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("floor_plan_image_path");

                    b.Property<Guid>("HousingPromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("housing_promotion_id");

                    b.Property<Guid?>("HousingTypologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("housing_typology_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal?>("UsableAreaSqm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("usable_area_sqm");

                    b.HasKey("Id");

                    b.HasIndex("HousingTypologyId");

                    b.HasIndex("HousingPromotionId", "Floor", "Door")
                        .IsUnique();

                    b.ToTable("housing_units", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_company_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperCompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kiwbi.Domain.Customizations.Customization", b =>
                {
                    b.HasOne("Kiwbi.Domain.Customizations.TradeCategory", null)
                        .WithMany()
                        .HasForeignKey("TradeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Kiwbi.Domain.Customizations.CustomizationAssignment", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CustomizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("customization_id");

                            b1.Property<Guid?>("HousingTypologyId")
                                .HasColumnType("uuid")
                                .HasColumnName("housing_typology_id");

                            b1.Property<Guid?>("HousingUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("housing_unit_id");

                            b1.Property<string>("Scope")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("scope");

                            b1.HasKey("Id");

                            b1.HasIndex("HousingTypologyId");

                            b1.HasIndex("HousingUnitId");

                            b1.HasIndex("CustomizationId", "HousingTypologyId")
                                .IsUnique()
                                .HasFilter("housing_typology_id IS NOT NULL");

                            b1.HasIndex("CustomizationId", "HousingUnitId")
                                .IsUnique()
                                .HasFilter("housing_unit_id IS NOT NULL");

                            b1.ToTable("customization_assignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomizationId");

                            b1.HasOne("Kiwbi.Domain.RealEstate.HousingTypology", null)
                                .WithMany()
                                .HasForeignKey("HousingTypologyId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Kiwbi.Domain.RealEstate.HousingUnit", null)
                                .WithMany()
                                .HasForeignKey("HousingUnitId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsMany("Kiwbi.Domain.Customizations.CustomizationOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CustomizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("customization_id");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<decimal>("SurchargeAmount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("surcharge_amount");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomizationId", "Name")
                                .IsUnique();

                            b1.ToTable("customization_options", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomizationId");
                        });

                    b.Navigation("Assignments");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Kiwbi.Domain.Customizations.TradeCategory", b =>
                {
                    b.HasOne("Kiwbi.Domain.RealEstate.HousingPromotion", null)
                        .WithMany()
                        .HasForeignKey("HousingPromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwbi.Domain.Developers.DeveloperCompany", b =>
                {
                    b.OwnsOne("Kiwbi.Domain.Developers.Branding", "Branding", b1 =>
                        {
                            b1.Property<Guid>("DeveloperCompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LogoPath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("logo_path");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("primary_color");

                            b1.Property<string>("SecondaryColor")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("secondary_color");

                            b1.HasKey("DeveloperCompanyId");

                            b1.ToTable("developer_companies");

                            b1.WithOwner()
                                .HasForeignKey("DeveloperCompanyId");
                        });

                    b.Navigation("Branding")
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingPromotion", b =>
                {
                    b.HasOne("Kiwbi.Domain.Developers.DeveloperCompany", null)
                        .WithMany()
                        .HasForeignKey("DeveloperCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingTypology", b =>
                {
                    b.HasOne("Kiwbi.Domain.RealEstate.HousingPromotion", null)
                        .WithMany()
                        .HasForeignKey("HousingPromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwbi.Domain.RealEstate.HousingUnit", b =>
                {
                    b.HasOne("Kiwbi.Domain.RealEstate.HousingPromotion", null)
                        .WithMany()
                        .HasForeignKey("HousingPromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwbi.Domain.RealEstate.HousingTypology", null)
                        .WithMany()
                        .HasForeignKey("HousingTypologyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kiwbi.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Kiwbi.Domain.Developers.DeveloperCompany", "DeveloperCompany")
                        .WithMany()
                        .HasForeignKey("DeveloperCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeveloperCompany");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kiwbi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kiwbi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwbi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kiwbi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
